# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ master, develop, feature/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub login
        run: docker login --username ${{ secrets.USERNAME_HUB }} --password ${{ secrets.PASSWORD_HUB }}
      - name: Build Docker
        run: docker build --tag ${{ secrets.USERNAME_HUB }}/cinema-admin:latest .
      - name: Push into DockerHub
        run: docker push ${{ secrets.USERNAME_HUB }}/cinema-admin:latest
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create SSH key file
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -A cinema@${{ secrets.SERVER_IP }} 'sudo docker stop cinema-admin; sudo docker rm cinema-admin; sudo docker rmi ${{ secrets.USERNAME_HUB }}/cinema-admin; sudo docker run -d -p 81:80 --name cinema-admin ${{ secrets.USERNAME_HUB }}/cinema-admin:latest;'
